2020-11-23 14:06:38,458 [INFO] root consoleworker.py:434	Log file created
2020-11-23 14:06:38,459 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7fde336ddb90> added
2020-11-23 14:06:38,460 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fde337267d0> added
2020-11-23 14:06:38,461 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fde336cb9d0> added
2020-11-23 14:06:38,462 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2020-11-23_14-06-38.352346
2020-11-23 14:06:38,463 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2020-11-23 14:06:38,464 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2020-11-23 14:06:38,466 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2020-11-23 14:06:38,467 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2020-11-23 14:06:38,467 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2020-11-23 14:06:38,476 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2020-11-23 14:06:38,477 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2020-11-23 14:06:38,478 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2020-11-23 14:06:38,479 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2020-11-23 14:06:38,480 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2020-11-23 14:06:38,481 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fde3341cf50>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fde3341ff10>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fde3341f6d0>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fde3341f590>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fde3341f4d0>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fde3341ce10>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fde3341c9d0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fde33746990>}
2020-11-23 14:06:38,482 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fde3341cf50>
2020-11-23 14:06:38,483 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2020-11-23 14:06:38,494 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-06-38.352346/answ_idb6bE.log
2020-11-23 14:06:38,499 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-06-38.352346/phout_i1SilM.log
2020-11-23 14:06:38,500 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_stat_32a3i3.log
2020-11-23 14:06:38,504 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_QOdjeL.log
2020-11-23 14:06:38,505 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 10.0.75.1:5555
2020-11-23 14:06:38,508 [DEBUG] yandextank.common.util util.py:516	Parsing port
2020-11-23 14:06:38,508 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('10.0.75.1', 5555)), (2, 2, 17, '', ('10.0.75.1', 5555)), (2, 3, 0, '', ('10.0.75.1', 5555))]
2020-11-23 14:06:38,508 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 10.0.75.1 and port 5555
2020-11-23 14:06:43,516 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [10.0.75.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2020-11-23 14:06:43,518 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [10.0.75.1]:5555
2020-11-23 14:06:43,520 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [10.0.75.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [10.0.75.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:06:43,526 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 10.0.75.1 and port 5555
2020-11-23 14:06:48,547 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [10.0.75.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2020-11-23 14:06:48,549 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [10.0.75.1]:5555
2020-11-23 14:06:48,551 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [10.0.75.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [10.0.75.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:06:48,554 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 10.0.75.1 and port 5555
2020-11-23 14:06:53,570 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [10.0.75.1]:5555 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2020-11-23 14:06:53,572 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [10.0.75.1]:5555
2020-11-23 14:06:53,574 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [10.0.75.1]:5555
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [10.0.75.1]:5555, use phantom.connection_test=0 to disable it
2020-11-23 14:06:53,582 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 10.0.75.1, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2020-11-23 14:06:53,593 [INFO] root consoleworker.py:269	Trying to clean up
2020-11-23 14:06:53,596 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_ViEC1L.lock
2020-11-23 14:06:53,608 [WARNING] root consoleworker.py:408	Job number is not available yet
2020-11-23 14:06:53,611 [WARNING] root consoleworker.py:415	Job number is not available yet
2020-11-23 14:06:53,631 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2020-11-23 14:06:53,632 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2020-11-23_14-06-38.352346
2020-11-23 14:06:53,633 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-06-38.352346/phout_i1SilM.log to /var/loadtest/logs/2020-11-23_14-06-38.352346/phout_i1SilM.log
2020-11-23 14:06:53,639 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-06-38.352346/phout_i1SilM.log
2020-11-23 14:06:53,641 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-06-38.352346/answ_idb6bE.log to /var/loadtest/logs/2020-11-23_14-06-38.352346/answ_idb6bE.log
2020-11-23 14:06:53,646 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-06-38.352346/answ_idb6bE.log
2020-11-23 14:06:53,648 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_stat_32a3i3.log to /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_stat_32a3i3.log
2020-11-23 14:06:53,655 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_stat_32a3i3.log
2020-11-23 14:06:53,657 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2020-11-23_14-06-38.352346/validation_error.yaml
2020-11-23 14:06:53,658 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2020-11-23 14:06:53,660 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_QOdjeL.log to /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_QOdjeL.log
2020-11-23 14:06:53,665 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2020-11-23_14-06-38.352346/phantom_QOdjeL.log
